SELECT a.CAR_ID, a.CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS a
INNER JOIN 
(SELECT CAR_TYPE, DISCOUNT_RATE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE IN ('세단', 'SUV')) AS C
ON a.CAR_TYPE = c.CAR_TYPE
AND a.CAR_ID NOT IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, a.CAR_TYPE, a.CAR_ID DESC;
